name: Test roulette

on:
#  schedule:
#    - cron: '* 10 * * *'
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.0

      - name: Install dependenciess
        run: npm ci

      - run: npm run test:metadata
        continue-on-error: true

      - uses: cakeinpanic/russian-roulette@master
        with:
          slack-token: ${{ secrets.SLACK_TOKEN}}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID}}
          fixers: UAL871MGQ,U01UFQAHDQE,U01UURVTHDJ,U01V0E30AQH,U01VBJ26QFJ


